const test = {
	user: {
		following: false,
		id: 616206,
		isBlocked: false,
		isScout: false,
		name: "Saint-Loup",
		url: "/Saint-Loup",
		username: "Saint-Loup",
		medias: {
			avatar: "https://media.senscritique.com/missing/3000/0x0/missing.png",
			backdrop: "https://media.senscritique.com/missing/2/400x0/missing.jpg",
			__typename: "UserMedias",
		},
		__typename: "User",
		settings: {
			about: "",
			birthDate: null,
			country: "France",
			dateLastSession: "2022-09-18T15:24:33.000Z",
			displayedName: "Saint-Loup",
			email: "shakespearien@gmail.com",
			firstName: "Baptiste",
			gender: null,
			lastName: "",
			privacyName: true,
			privacyProfile: false,
			showAge: false,
			showProfileType: 8,
			urlWebsite: "http://toutcequibouge.net",
			username: "Saint-Loup",
			zipCode: "",
			__typename: "UserSettings",
		},
		collection: {
			filters: {
				releaseDate: null,
				__typename: "CollectionFilters",
			},
			__typename: "Collection",
		},
		ratingsStats: {
			rating1: 1,
			rating2: 1,
			rating3: 8,
			rating4: 11,
			rating5: 9,
			rating6: 7,
			rating7: 24,
			rating8: 26,
			rating9: 9,
			rating10: 0,
			__typename: "StatsSplit",
		},
		stats: {
			collectionCount: 1158,
			followerCount: 2,
			id: 616206,
			listCount: 1,
			ratingCount: 96,
			reviewCount: 0,
			scoutCount: 2,
			__typename: "UserStats",
		},
	},
};